In [4]:
import pandas as pd

path = r"C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\evaluation\golden_answers_dataset.jsonl"

import json

with open(path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        line=line.strip()
        if not line:
            print(f"⚠️ Empty line at {i}")
            continue
        try:
            json.loads(line)
        except Exception as e:
            print(f"❌ Error in line {i}: {e} -> {line}")

import pandas as pd


df = pd.read_json(path, lines=True)
df.head()

,id,query_type,question,gold_answer
0,1,factual,Which pins of the Arduino Nano 33 BLE support ...,The Arduino Nano 33 BLE supports PWM on pins D...
1,2,factual,What is the input voltage range for the VIN pi...,The VIN pin on the Arduino Uno accepts 7–12 V ...
2,3,factual,What is the flash memory size of the Arduino N...,The Arduino Nano 33 IoT provides 256 KB of fla...
3,4,factual,Which hardware serial interfaces are available...,The Arduino Mega 2560 offers four hardware ser...
4,5,factual,What is the default I2C address of the MPU6050...,The MPU6050 defaults to address 0x68 when AD0 ...

In [4]:
path = r"C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\evaluation\answers_log.csv"

import pandas as pd

df = pd.read_csv(path)

df.head(5)

,retriever_new.py,21,Can I connect 5V to Nano 33 BLE Sense?,"No, you should not directly connect 5V signals to the Nano 33 BLE Sense board. The board is designed to operate with 3.3V I/Os and it is NOT 5V tolerant.\n\nTo power the board using a higher voltage source, you would need to use a level shifter or a voltage regulator that can step down the 5V signal to the safe 3.3V level for the Nano 33 BLE Sense board."
0,retriever_new.py,18,Why can the Arduino Uno fail to reliably read ...,"The Arduino Uno, while capable of handling 3.3..."